version: '3.4'

services:
  backend:
    image: ${DOCKER_REGISTRY-}api
    container_name: backend
    hostname: backend
    build:
      context: .
      dockerfile: api/Dockerfile
    depends_on:
      - postgres_db
    networks:
      - local_net

  postgres_db:
    container_name: postgres
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1
      - POSTGRES_DB=finshark
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - local_net

volumes:
  postgres-data:

networks:
  local_net:
    external: true
    driver: bridge
    name: services
